'use strict';
var ROUTES=['methodologies','evidence','readiness','exceptions','review','packages'];
var ROUTE_LABELS=['Methodology','Evidence','Evaluation','Exception','Human Review','Monitoring Package'];
var UI={activityId:null,message:'',error:false,evidencePage:0,inspect:false,busy:false};
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function activeRoute(){var p=(location.hash||'#/methodologies').slice(2);if(typeof REVIEWER_DEMO_ROUTE!=='undefined'&&p===REVIEWER_DEMO_ROUTE)return p;return ROUTES.indexOf(p)>=0?p:'methodologies';}
function selectedActivity(){var list=visibleActivities();return list.find(function(a){return a.id===UI.activityId;})||list[0]||null;}
function button(label,action,disabled){return '<button data-action="'+action+'" '+(disabled||UI.busy?'disabled':'')+'>'+esc(label)+'</button>';}
function jsonView(value){return '<pre>'+esc(JSON.stringify(value,null,2))+'</pre>';}
function currentEvaluation(a){var r=a&&latestEvaluation(a);return r&&evaluationCurrent(a,r)?r:null;}
function blankActivity(){return '<section class="card"><h2>活動を登録してください</h2><p>Operatorで圃場と活動期間を登録すると、証憑からパッケージまで進められます。</p><a href="#/evidence">Evidenceへ</a></section>';}
function reviewerHeader(){
  return '<header class="reviewer-header"><a class="reviewer-home" href="#/methodologies">NaFT研究UIへ</a><span class="eyebrow">NaFT · Research Prototype</span><h1>Reviewer Demo</h1><p>Version-aware MRV Evidence Compiler + Re-verification Engine</p></header>';
}
function header(route){
  if(typeof REVIEWER_DEMO_ROUTE!=='undefined'&&route===REVIEWER_DEMO_ROUTE) return reviewerHeader();
  var a=selectedActivity();
  return '<header><span class="eyebrow">NaFT · MRV research prototype</span><h1>Version-aware MRV<br>Evidence Compiler</h1><p>NaFT transforms heterogeneous environmental evidence into methodology-aware, reproducible, human-reviewable MRV packages.</p><div class="row"><label>Demo actor <select id="actor" '+(UI.busy?'disabled':'')+'>'+db.users.map(function(u){return '<option value="'+esc(u.id)+'"'+(actorId===u.id?' selected':'')+'>'+esc(u.name)+'</option>';}).join('')+'</select></label><label>Selected field / activity <select id="activity" '+(UI.busy?'disabled':'')+'><option value="">Select activity</option>'+visibleActivities().map(function(x){return '<option value="'+esc(x.id)+'"'+(a&&a.id===x.id?' selected':'')+'>'+esc(x.field_id+' / '+x.crop_year)+'</option>';}).join('')+'</select></label><span class="pill">Client-side demo identities</span></div><a class="reviewer-cta" href="#/reviewer-demo">Mitou Reviewer Demoを開く →</a><nav aria-label="MRV workflow">'+ROUTES.map(function(r,i){return '<a href="#/'+r+'"'+(r===route?' aria-current="page"':'')+'>'+(i+1)+'. '+ROUTE_LABELS[i]+'</a>';}).join('')+'</nav><div class="notice"><b>CONFIG REQUIRED</b> · AG-005参照版。正式採択版と適用係数は未確認です。内部チェック・宣誓によって正式認証にはなりません。</div></header>';
}
function pgMethodologies(){var pack=AG005_RULE,key=pack.methodology_id+'@'+pack.methodology_version,r=packRelease(pack);return '<section class="card"><span class="eyebrow">1 / Methodology registry</span><h2>Rule Packを版で固定する</h2><p>従来のAG-005参照評価です。上のCompilerは複数のVersioned Packを扱います。評価には方法論版・実装ルール版・計算版・証憑Adapter版とPackのSHA-256を固定します。</p><table><tbody>'+['methodology_id','methodology_version','rule_version','calculation_version','adapter_version','source_status'].map(function(k){return '<tr><th>'+esc(k)+'</th><td>'+esc(pack[k])+'</td></tr>';}).join('')+'</tbody></table><p>Pack hash: <code>'+hashObject(pack)+'</code></p><p>Prototype release: <b>'+esc(validRelease(pack)?'HUMAN APPROVED':r?'INTEGRITY ERROR':'AWAITING MAINTAINER')+'</b></p><p>Packのrelease approvalは参照実装の利用承認です。制度の採択確認や係数確定を意味しません。</p>'+(!r?'<label>Pack release rationale<textarea id="pack-note" placeholder="参照版として確認した範囲と未解決点を記録してください（20文字以上）"></textarea></label>'+button('Approve prototype Rule Pack','release',!currentUser()||currentUser().role!=='maintainer'):'<p>'+esc(r.note)+'</p>')+'<a href="#/evidence">Evidenceへ →</a></section>';}
function registration(a){return '<details class="card"'+(!a?' open':'')+'><summary>Program → Farmer → Field → Activityを登録</summary><p>入力例は架空データです。圃場ID・期間・基準年を確認してください。同一圃場の重複／重なる活動を拒否します。</p><label>Activity JSON<textarea id="activity-json" rows="16">'+esc(JSON.stringify(exampleActivity(),null,2))+'</textarea></label>'+button('Register activity','register',currentUser().role!=='operator')+'</details>';}
function pgEvidence(a){
  var out=registration(a);if(!a)return out;
  var ev=evidenceFor(a),assessment=evaluateSnapshot(snapshotFor(a)),pages=Math.max(1,Math.ceil(ev.length/10)),page=Math.min(UI.evidencePage,pages-1),rows=ev.slice(page*10,page*10+10),locked=!!attestationFor(a);
  out+='<section class="card"><span class="eyebrow">2 / Evidence adapter</span><h2>'+esc(a.field_id)+' · 証憑をManifestへ</h2><p>ファイルの実バイトをSHA-256で記録します。本文の解析・保管・真正性判断は行いません。最大5 MiB。</p><p>Required categories: '+assessment.evidence_completeness.present+' / '+assessment.evidence_completeness.required+'</p><div class="row"><label>Category / year<select id="evidence-spec">'+assessment.evidence_completeness.missing.map(function(t){return '<option>'+esc(t)+'</option>';}).join('')+'</select></label><label>Original file<input type="file" id="evidence-file"></label><label>Source<input id="evidence-source" value="Operator-provided original"></label></div>'+button('Hash selected file','attach',locked||currentUser().role!=='operator')+button('Add SYNTHETIC demo evidence','sample',locked||currentUser().role!=='operator')+'<p class="muted">SYNTHETICデータはパイプライン検証専用で、現場観測ではありません。</p><div class="scroll"><table><thead><tr><th>File / type</th><th>Year</th><th>Hash</th><th>Source</th></tr></thead><tbody>'+rows.map(function(e){return '<tr><td>'+esc(e.original_filename)+'<br>'+esc(e.evidence_type)+'</td><td>'+esc(e.crop_year)+'</td><td><code>'+esc(e.hash.slice(0,16))+'…</code></td><td>'+esc(e.source.slice(0,100))+'</td></tr>';}).join('')+'</tbody></table></div>'+button('Previous','previous',page===0)+'<span>Page '+(page+1)+' / '+pages+'</span>'+button('Next','next',page+1>=pages)+'<div class="row"><label>Recheck manifest (this page)<select id="recheck-id">'+rows.map(function(e){return '<option value="'+esc(e.evidence_id)+'">'+esc(e.original_filename)+'</option>';}).join('')+'</select></label><label>Original for recheck<input type="file" id="recheck-file"></label></div>'+button('Verify content hash','recheck',!rows.length)+button(UI.inspect?'Close manifest JSON':'Inspect page manifests','inspect',false)+(UI.inspect?jsonView(rows):'')+'<p><a href="#/readiness">Evaluationへ →</a></p></section>';
  return out;
}
function pgReadiness(a){if(!a)return blankActivity();var r=currentEvaluation(a),old=latestEvaluation(a);return '<section class="card"><span class="eyebrow">3 / Deterministic evaluation</span><h2>機械が評価し、例外を抽出する</h2><p>証憑充足・hash・方法論版・日付・重複・計算を決定論的に検査します。実行操作は承認ではありません。パッケージ下書きは評価結果から自動構築されます。</p>'+button('Evaluate activity','evaluate',!!attestationFor(a))+'<p><b>'+esc(r?r.result.status:old?'STALE — 入力または評価が変更されています':'NOT EVALUATED')+'</b></p>'+(r?'<div class="scroll"><table><thead><tr><th>Check</th><th>Result</th><th>Detail</th></tr></thead><tbody>'+r.result.checks.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+esc(c.status)+'</td><td>'+esc(c.note)+'</td></tr>';}).join('')+'</tbody></table></div><h3>Calculation Assist</h3><p>Illustrative arithmetic: '+esc(r.result.calculation.arithmetic_preview===null?'Unavailable':r.result.calculation.arithmetic_preview)+' · certified result: null</p><details><summary>Calculation inputs / formula</summary>'+jsonView(r.result.calculation)+'</details>':'')+'<p><a href="#/exceptions">Exceptionへ →</a></p></section>';}
function pgExceptions(a){if(!a)return blankActivity();var r=currentEvaluation(a);if(!r)return '<section class="card">現在の入力を<a href="#/readiness">評価</a>してください。</section>';return '<section class="card"><span class="eyebrow">4 / Human-on-the-exception</span><h2>判断が必要な案件だけを人間へ</h2><p>FAIL・MISSING・未対応条件は上書き承認できません。証憑の競合には原本確認と理由を要求します。例外がない案件に追加の承認操作はありません。</p>'+(!r.result.exceptions.length?'<p><b>例外なし。最終パッケージ宣誓へ進めます。</b></p>':r.result.exceptions.map(function(e){var d=decisionsFor(r).find(function(x){return x.exception_id===e.id;});return '<article class="card"><h3>'+esc(e.id)+' <span class="pill">'+esc(e.kind)+'</span></h3><p>'+esc(e.detail)+'</p>'+(d?'<p>Decision: '+esc(validDecision(d)?d.decision:'INTEGRITY ERROR')+' · '+esc(d.note)+'</p>':'<label>Human rationale<textarea data-note="'+esc(e.id)+'"></textarea></label><button data-action="accept-exception" data-id="'+esc(e.id)+'" '+(e.kind==='blocking'||currentUser().role!=='reviewer'||UI.busy?'disabled':'')+'>Accept with reason</button><button data-action="reject-exception" data-id="'+esc(e.id)+'" '+(currentUser().role!=='reviewer'||UI.busy?'disabled':'')+'>Reject</button>')+'</article>';}).join(''))+'<a href="#/review">Human Reviewへ →</a></section>';}
function pgReview(a){if(!a)return blankActivity();var r=currentEvaluation(a),record=attestationFor(a);return '<section class="card"><span class="eyebrow">5 / Human-at-the-attestation</span><h2>最終パッケージに一度だけ宣誓する</h2><p>原資料の意味・証憑の対応関係・持続可能性の申告・未解決の制度設定を確認してください。通常案件には途中承認を要求しません。</p><p>Rule Pack release: '+(validRelease(methodologyPack(a))?'HUMAN APPROVED':'MAINTAINER APPROVAL REQUIRED')+'<br>Outstanding exceptions: '+(r?unresolvedExceptions(r).length:'evaluation required')+'</p>'+(record?'<p><b>ATTESTED · research package only</b></p><p>'+esc(record.document.attestation.statement)+'</p>':'<label>Final attestation statement<textarea id="attestation-note" placeholder="確認した証憑と残る制約を記録してください（20文字以上）"></textarea></label><label><input type="checkbox" id="attestation-ack"> 原資料と例外判断を確認し、CONFIG REQUIREDが残る研究用パッケージへの宣誓であり正式認証ではないことを理解しました。</label>'+button('Attest final package','attest',!r||!!unresolvedExceptions(r).length||!validRelease(methodologyPack(a))||currentUser().role!=='reviewer'))+'<p><a href="#/packages">Monitoring Packageへ →</a></p></section>';}
function pgPackages(a){if(!a)return blankActivity();var r=currentEvaluation(a),record=attestationFor(a),agg=programAggregate(a.program_id);return '<section class="card"><span class="eyebrow">6 / Monitoring package</span><h2>再現可能なMRVパッケージ</h2><p>版を固定したRule Pack・入力snapshot・評価・例外判断・来歴をJSONへ。宣誓済み文書は保存時の内容とhashを保ち、無関係な監査イベントの追加で書き換わりません。</p>'+button('Export package draft JSON','export-draft',!r)+button('Export attested package JSON','export-attested',!record)+'<p>'+esc(record?'Attested hash: '+record.package_hash:'Final attestation not recorded')+'</p><details><summary>Program aggregation · saved counts</summary>'+jsonView(agg)+'</details><p>集計は保存件数です。各案件の完全性は評価・export時に検査します。</p>'+button('Verify audit chain','audit',false)+'<p class="muted">監査結果は操作時の検証です。書き込み・判断・exportでは必ず全チェーンを再確認します。</p></section>';}
function render(){
  var route=activeRoute(),a=selectedActivity(),page;
  try{
    if(typeof REVIEWER_DEMO_ROUTE!=='undefined'&&route===REVIEWER_DEMO_ROUTE) page=pgReviewerDemo();
    else page={methodologies:pgMethodologies,evidence:pgEvidence,readiness:pgReadiness,exceptions:pgExceptions,review:pgReview,packages:pgPackages}[route](a);
  }catch(e){page='<section class="card error">表示を停止しました: '+esc(e.message)+'</section>';}
  var compiler=(typeof REVIEWER_DEMO_ROUTE!=='undefined'&&route===REVIEWER_DEMO_ROUTE)?'':(typeof compilerPanel==='function'?compilerPanel(route):'');
  document.getElementById('app').innerHTML=header(route)+'<main><div class="status '+(UI.error?'error':'')+'" role="status" aria-live="polite">'+esc(UI.message)+'</div>'+compiler+page+'</main><footer>'+esc(DISCLAIMER)+'<p>Data: '+(typeof window.storage!=='undefined'?'Artifact storage':'this browser session only; reload clears data')+'</p></footer>';
}
function readValue(id){var el=document.getElementById(id);return el?el.value:'';}
async function addSampleEvidence(a){var needs=evaluateSnapshot(snapshotFor(a)).evidence_completeness.missing;for(var spec of needs){var parts=spec.split(':'),bytes=new TextEncoder().encode('SYNTHETIC DEMO — not field evidence\n'+canonicalize({activity:a,type:parts[0],year:parts[1]}));await attachEvidence(a.id,{name:'synthetic-'+spec+'.txt',size:bytes.length,arrayBuffer:(function(b){return async function(){return b.buffer;};})(bytes)},parts[0],Number(parts[1]),'SYNTHETIC DEMO generated bytes');}}
function downloadJSON(text,name){var url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
async function handleAction(action,el){
  if(UI.busy)return;
  var a=selectedActivity();UI.error=false;UI.message='';
  // Pure view toggles retain the exact input nodes, including selected File objects.
  if(['previous','next','inspect'].indexOf(action)>=0){var ids=['activity-json','evidence-spec','evidence-file','evidence-source','recheck-id','recheck-file'],nodes={};ids.forEach(function(id){var node=document.getElementById(id);if(node)nodes[id]=node;});if(action==='inspect')UI.inspect=!UI.inspect;else UI.evidencePage=Math.max(0,UI.evidencePage+(action==='next'?1:-1));render();Object.keys(nodes).forEach(function(id){var fresh=document.getElementById(id);if(fresh&&id!=='recheck-id')fresh.replaceWith(nodes[id]);});return;}
  UI.busy=true;document.querySelectorAll('button,#actor,#activity').forEach(function(node){node.disabled=true;});
  try{
    if(action.indexOf('compiler-')===0&&typeof handleCompilerAction==='function')await handleCompilerAction(action,el);
    if(action.indexOf('reviewer-')===0&&typeof handleReviewerAction==='function')handleReviewerAction(action,el);
    if(action==='release'){await approvePack('AG-005@3.1-reference',readValue('pack-note'));UI.message='Reference Rule Pack approved for prototype use.';}
    if(action==='register'){a=await registerActivity(JSON.parse(readValue('activity-json')));UI.activityId=a.id;UI.message='Activity registered.';}
    if(action==='attach'){var spec=readValue('evidence-spec').split(':');await attachEvidence(a.id,document.getElementById('evidence-file').files[0],spec[0],Number(spec[1]),readValue('evidence-source'));UI.message='Evidence manifest recorded; evaluate current inputs.';}
    if(action==='sample'){await addSampleEvidence(a);UI.message='SYNTHETIC evidence recorded; no real field observations.';}
    if(action==='recheck')UI.message=await verifyEvidenceContent(readValue('recheck-id'),document.getElementById('recheck-file').files[0]);
    if(action==='evaluate'){var r=await evaluateActivity(a.id);UI.message=r.result.status+' · package draft constructed from the evaluation.';}
    if(action==='accept-exception'||action==='reject-exception'){var box=Array.from(document.querySelectorAll('[data-note]')).find(function(n){return n.dataset.note===el.dataset.id;});await decideException(a.id,el.dataset.id,action==='accept-exception'?'accept_with_reason':'reject',box.value);UI.message='Human exception decision recorded.';}
    if(action==='attest'){await attestPackage(a.id,readValue('attestation-note'),document.getElementById('attestation-ack').checked);UI.message='Final package attested; formal verification not performed.';}
    if(action==='export-draft'||action==='export-attested'){var text=exportMonitoringJSON(a.id,action==='export-attested');downloadJSON(text,'naft-mrv-'+a.id+'.json');UI.message='Monitoring Package exported.';}
    if(action==='audit')UI.message='Audit chain: '+verifyAuditChain().status+' · checked at '+nowISO();
  }catch(e){UI.error=true;UI.message='BLOCKED: '+e.message;}
  UI.busy=false;render();
}
async function startApp(){
  try{await loadDB();render();}catch(e){document.getElementById('app').innerHTML='<main><h1>NaFT · MRV Core</h1><p class="error">保存データの読込を停止しました: '+esc(e.message)+'</p></main>';return;}
  window.addEventListener('hashchange',function(){UI.inspect=false;render();});
  document.getElementById('app').addEventListener('click',function(event){var el=event.target.closest('[data-action]');if(el&&!el.disabled)handleAction(el.dataset.action,el);});
  document.getElementById('app').addEventListener('change',function(event){if(UI.busy)return;if(event.target.id==='actor'){setActor(event.target.value);UI.activityId=null;}else if(event.target.id==='activity')UI.activityId=event.target.value;else return;UI.evidencePage=0;UI.inspect=false;UI.message='';render();});
}
if(typeof window!=='undefined'&&typeof document!=='undefined')startApp();
